
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[306] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      102,  100,    9,    4,    4,  100,  100,    3,   36,   64,
      100,   19,   20,   30,   28,   26,   29,   35,   31,   96,
       96,   25,   27,   32,   34,   33,   62,   97,   97,   97,
       97,   21,  100,   22,   44,   37,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   23,   54,   24,   43,    9,    3,   17,   15,
       15,   17,   17,   17,    8,    8,    6,    5,    7,    6,
        6,   98,    9,    4,   39,    0,   18,    0,    3,   52,
       53,    0,   18,    0,   47,   50,   48,   49,   95,   60,

       51,   95,   96,    0,   96,    0,    0,   96,    0,   45,
       40,   42,   38,   41,   46,   97,    0,    0,   97,   97,
       97,   10,   10,   56,    0,   97,   67,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   82,   97,
       84,   85,   97,   97,   66,   97,   97,   97,   97,   97,
       97,   97,   97,   55,    9,    0,    3,    1,    1,   15,
        0,   16,    0,    8,    5,    7,    7,    7,    0,    1,
       18,   13,   11,   59,   61,   96,   96,   96,    0,   95,
       57,   58,    0,   63,   97,   97,   97,   97,   72,   73,
       97,   97,   97,   97,   97,   97,   79,   97,   97,   97,

       97,   65,   97,   97,   97,   97,   91,   97,   97,   97,
       12,   14,    0,   97,   97,   97,   97,   97,   74,   75,
       97,   77,   97,   80,   97,   97,   97,   87,   97,   97,
       97,   97,   93,   97,    0,   97,   69,   70,   97,   97,
       97,   97,   97,   97,   97,   88,   89,   97,   92,   94,
        0,   68,   97,   97,   76,   97,   81,   83,   86,   90,
        2,    2,   97,   97,   78,   71,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   99,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    1,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   31,   31,   33,   34,
       35,   35,   35,   36,   35,   37,   35,   35,   38,   35,
       35,   39,   35,   35,   40,   35,   35,   41,   35,   35,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   36,   57,   58,   59,   60,
       61,   62,   35,   63,   64,   65,   66,   35,   67,   68,
       69,   35,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    2,    3,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    1,    5,    1,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[317] =
    {   0,
        0,   72,   72,   77,   80,   87,   88,   94,  503,  502,
      504,  507,  100,  507,  500,  474,   71,    0,  473,  472,
       74,  507,  507,   79,  471,  507,  470,   87,   85,  112,
      105,  507,  507,  118,  469,   90,  507,    0,  128,  143,
      127,  507,  134,  507,   73,  507,   52,  132,   64,  100,
       96,  118,  438,  125,  447,  433,  430,  138,  110,  429,
      113,  435,  507,  462,  507,  507,  198,  191,  507,  507,
      486,  476,    0,  479,  507,  483,  507,  208,  507,  482,
      194,  507,  214,  507,  507,  179,  476,  220,    0,  507,
      507,  176,  471,  223,  454,  507,  507,  507,  208,  453,

      507,  212,  216,  221,  507,  228,    0,  233,  255,  452,
      507,  507,  507,  507,  451,    0,  197,  203,  250,  251,
      253,  507,  475,  507,  410,  425,  411,  260,  426,  413,
      150,  408,  211,  230,  411,  407,  408,  407,    0,  405,
        0,    0,  407,  400,    0,  400,  407,  406,  396,  391,
      403,  393,  405,  507,  284,  278,  284,  507,  289,  507,
      444,  507,  447,  507,  293,  507,  451,  507,  298,  301,
      507,  507,  507,  507,  507,  286,  288,  247,  292,  296,
      507,  507,  389,    0,  400,  403,  386,  384,    0,    0,
      386,  394,  394,  393,  394,  395,    0,  383,  392,  379,

      390,    0,  374,  377,  372,  369,    0,  376,  378,  374,
      507,  507,  359,  367,  372,  364,  371,  368,    0,    0,
      363,    0,  366,    0,  375,  359,  370,    0,  355,  367,
      355,  365,    0,  365,  400,  349,    0,    0,  353,  364,
      346,  352,  351,  343,  359,    0,    0,  346,    0,    0,
      319,    0,  339,  335,    0,  334,    0,    0,    0,    0,
      507,  399,  349,  354,    0,    0,  347,  335,  334,  335,
      332,  328,  314,  308,  316,  301,  304,  289,  283,  294,
      276,  288,  288,  332,  279,  275,  275,  280,  327,  267,
      265,  266,  272,  267,  272,  315,  252,  182,  215,  160,

      127,   98,   95,  507,  507,  346,  351,  356,  361,  366,
      371,  373,  378,  383,  388,   83
    } ;

static yyconst flex_int16_t yy_def[317] =
    {   0,
      305,    1,  306,  306,  306,  306,  307,  308,  307,  307,
      305,  305,  305,  305,  305,  305,  309,  310,  305,  305,
      311,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  312,  312,  312,
       40,  305,  305,  305,  305,  305,  312,   40,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,   40,  312,
      312,  312,  305,  305,  305,  305,  305,  313,  305,  305,
      305,  305,  314,  305,  305,  305,  305,  305,  305,  305,
      315,  305,  305,  305,  305,  309,  305,  309,  310,  305,
      305,  311,  305,  311,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,  305,  305,  316,  305,  305,  305,
      305,  305,  305,  305,  305,  312,  309,  311,  312,  312,
      312,  305,  305,  305,  305,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  305,  305,  315,  313,  305,  313,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  315,  315,
      305,  305,  305,  305,  305,  305,  305,  316,  305,  305,
      305,  305,  305,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      305,  305,  305,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  305,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      305,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      305,  305,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,    0,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305
    } ;

static yyconst flex_uint16_t yy_nxt[581] =
    {   0,
       12,   13,   14,   13,   15,   13,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   31,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   38,   38,   38,   38,   38,   38,   40,   41,
       38,   42,   43,   44,   45,   38,   46,   47,   48,   49,
       50,   51,   52,   53,   38,   54,   38,   55,   38,   56,
       57,   58,   59,   38,   60,   41,   61,   38,   62,   63,
       64,   65,   66,   67,   70,   67,   71,   67,   87,   70,
       68,   71,   70,   72,   71,   93,  178,   74,   72,   70,
       75,   71,   76,   95,   74,   78,   79,   78,   80,   78,

      124,   83,   81,   83,  100,   83,   96,   99,   99,   99,
       99,  126,  101,   88,   73,  127,   94,  114,  115,   73,
      304,  129,   73,  102,  130,  108,  108,  108,  108,   73,
      102,  303,  103,  103,  103,  117,  122,  109,  123,  118,
      105,  105,  125,  104,  110,  111,  112,  105,  105,  106,
      117,  131,  107,  133,  118,  132,  109,  148,  116,  119,
      104,  149,  105,  134,  302,  121,  119,  151,  152,  105,
      119,  116,  106,  135,  119,  116,  119,  139,  136,  107,
      137,  120,  121,  140,  141,  146,  171,  171,  142,  121,
      119,  119,  301,  158,  128,  159,  158,  116,  170,  155,

      147,  155,  189,  155,   87,  120,  156,  190,  121,  165,
      166,  165,  167,  165,   93,   83,  156,   83,   94,   83,
      300,   88,   86,   86,   86,   92,   92,   92,   99,   99,
       99,   99,   99,   99,   99,   99,  103,  103,  103,   88,
      109,  176,  176,  105,  109,   94,  299,  105,  177,  177,
      177,  102,  105,  108,  108,  108,  108,  117,  117,  109,
      117,  118,  118,  109,  118,  109,  192,  117,  105,  105,
      179,  118,  179,  105,  193,  180,  180,  180,  180,  194,
      158,  195,  170,  105,  109,  155,  158,  155,  159,  155,
      105,  158,  156,  159,  165,  166,  165,  167,  165,  298,

      158,  156,  170,  158,  105,  170,  176,  176,  177,  177,
      177,  186,  180,  180,  180,  180,  180,  180,  180,  180,
      297,  261,  105,  262,  105,  296,  295,  294,  293,  292,
      291,  105,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  105,  279,  105,   69,   69,   69,   69,
       69,   12,   12,   12,   12,   12,   77,   77,   77,   77,
       77,   86,  278,  277,   86,   86,   89,  276,   89,   89,
       89,   92,  275,  274,   92,   92,  116,  116,  157,  157,
      157,  157,  157,  162,  162,  162,  162,  162,  169,  169,
      169,  169,  169,  273,  272,  271,  270,  269,  268,  267,

      266,  261,  265,  264,  263,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  166,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  191,  188,  187,  185,  184,  183,  122,  182,  181,
      175,  174,  173,  172,  168,  164,  163,  161,  160,  154,
      153,  150,  145,  144,  143,  138,  113,   98,   97,   91,

       90,   85,   84,  305,   82,   82,   11,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst flex_int16_t yy_chk[581] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    2,    3,    2,   17,    4,
        2,    4,    5,    3,    5,   21,  316,    5,    4,    6,
        7,    6,    7,   24,    6,    8,    8,    8,    8,    8,

       45,   13,    8,   13,   29,   13,   24,   28,   28,   28,
       28,   47,   29,   17,    3,   47,   21,   36,   36,    4,
      303,   49,    5,   31,   49,   31,   31,   31,   31,    6,
       30,  302,   30,   30,   30,   39,   43,   31,   43,   39,
       31,   31,   45,   30,   34,   34,   34,   30,   30,   30,
       40,   50,   30,   51,   40,   50,   31,   59,   41,   39,
       30,   59,   31,   51,  301,   41,   39,   61,   61,   30,
       48,   48,   30,   52,   40,   41,   39,   54,   52,   30,
       52,   40,   40,   54,   54,   58,   86,   92,   54,   41,
       39,   40,  300,   68,   48,   68,   81,   48,   81,   67,

       58,   67,  131,   67,  117,   40,   67,  131,   40,   78,
       78,   78,   78,   78,  118,   83,   78,   83,   92,   83,
      299,   86,   88,   88,   88,   94,   94,   94,   99,   99,
       99,   99,  102,  102,  102,  102,  103,  103,  103,  117,
       99,  104,  104,   99,  102,  118,  298,  102,  106,  106,
      106,  108,  103,  108,  108,  108,  108,  119,  120,   99,
      121,  119,  120,  102,  121,  108,  133,  128,  108,  108,
      109,  128,  109,  103,  133,  109,  109,  109,  109,  134,
      156,  134,  156,  178,  108,  155,  157,  155,  157,  155,
      108,  159,  155,  159,  165,  165,  165,  165,  165,  297,

      169,  165,  169,  170,  178,  170,  176,  176,  177,  177,
      177,  128,  179,  179,  179,  179,  180,  180,  180,  180,
      296,  251,  176,  251,  177,  295,  294,  293,  292,  291,
      290,  180,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  176,  278,  177,  306,  306,  306,  306,
      306,  307,  307,  307,  307,  307,  308,  308,  308,  308,
      308,  309,  277,  276,  309,  309,  310,  275,  310,  310,
      310,  311,  274,  273,  311,  311,  312,  312,  313,  313,
      313,  313,  313,  314,  314,  314,  314,  314,  315,  315,
      315,  315,  315,  272,  271,  270,  269,  268,  267,  264,

      263,  262,  256,  254,  253,  248,  245,  244,  243,  242,
      241,  240,  239,  236,  235,  234,  232,  231,  230,  229,
      227,  226,  225,  223,  221,  218,  217,  216,  215,  214,
      213,  210,  209,  208,  206,  205,  204,  203,  201,  200,
      199,  198,  196,  195,  194,  193,  192,  191,  188,  187,
      186,  185,  183,  167,  163,  161,  153,  152,  151,  150,
      149,  148,  147,  146,  144,  143,  140,  138,  137,  136,
      135,  132,  130,  129,  127,  126,  125,  123,  115,  110,
      100,   95,   93,   87,   80,   76,   74,   72,   71,   64,
       62,   60,   57,   56,   55,   53,   35,   27,   25,   20,

       19,   16,   15,   11,   10,    9,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[102] =
    {   0,
1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
/*
 * The MIT License (MIT)
 * 
 * Copyright (c) 2016 Brian A. Malloy and James F. Power
 * 
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 * 
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 */
#line 27 "scan.l"
/* This scanner is written by James Power, Chris Malloy, and Brian Malloy
 * During Fall, 2016.  
 * Most of the definitions and specifications were taken from:
 * https://docs.python.org/2.7/reference/index.html
 */

#include "ast.h"
#include "parse.tab.h"
#include <stack>

  /* The scanner state: */
  static std::stack<int> indentations;
  static int curr_indent = 0;
  static int encmatching = 0;
  static bool given_endmarker = false;

  static void display_error(const char *msg);
  static int iced(const int);
  static int calc_indent_change(const int);
  static int handle_indent(const int);
  static void left_enclose(void);
  static void right_enclose(void);

  /* Some counters, just for information: */
  static int keywords = 0;
  static int identifiers = 0;
  static int numbers = 0;
#define YY_USER_ACTION yylval.ast = NULL;
/***** Start states for multi-line strings and indentation *****/




#line 773 "lex.yy.c"

#define INITIAL 0
#define LONG_STRING 1
#define LONG_STRING2 2
#define INDENTING 3
#define FINISHING 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 129 "scan.l"


#line 1001 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 507 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 131 "scan.l"
{ BEGIN(INDENTING); }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 132 "scan.l"
{ BEGIN(INDENTING); return NEWLINE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 134 "scan.l"
{ ; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 136 "scan.l"
{ 
                              BEGIN(INDENTING);
                              if(encmatching <= 0);
                              {
                                  return NEWLINE; 
                              }
                            }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 144 "scan.l"
{ int t = handle_indent(yyleng); if( t > 0 ) return t; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 145 "scan.l"
{ int t = handle_indent(0);  if( t > 0 ) return t; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 146 "scan.l"
{ /* Entirely blank line: do nothing */ }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 147 "scan.l"
{ /* Entirely blank line: do nothing */ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 149 "scan.l"
{ ; }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 150 "scan.l"
{  /* Explicit line joining: throw it away */ ;  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 153 "scan.l"
{ BEGIN(LONG_STRING); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 154 "scan.l"
{ BEGIN(INITIAL); return STRING; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 156 "scan.l"
{ BEGIN(LONG_STRING2); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 157 "scan.l"
{ BEGIN(INITIAL); return STRING; }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 159 "scan.l"
{ ; }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 160 "scan.l"
{ ; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 161 "scan.l"
{ ; }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 163 "scan.l"
{ return STRING; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 166 "scan.l"
{ left_enclose();  return LPAR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 167 "scan.l"
{ right_enclose(); return RPAR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 168 "scan.l"
{ left_enclose();  return LSQB;  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 169 "scan.l"
{ right_enclose(); return RSQB; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 170 "scan.l"
{ left_enclose();  return LBRACE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 171 "scan.l"
{ right_enclose(); return RBRACE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 173 "scan.l"
{ return COLON; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 174 "scan.l"
{ return COMMA; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 175 "scan.l"
{ return SEMI; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 177 "scan.l"
{ return PLUS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 178 "scan.l"
{ return MINUS; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 179 "scan.l"
{ return STAR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 180 "scan.l"
{ return SLASH; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 182 "scan.l"
{ return LESS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 183 "scan.l"
{ return GREATER; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 184 "scan.l"
{ return EQUAL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 186 "scan.l"
{ return DOT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 187 "scan.l"
{ return PERCENT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 188 "scan.l"
{ return BACKQUOTE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 190 "scan.l"
{ return EQEQUAL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 191 "scan.l"
{ return NOTEQUAL; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 192 "scan.l"
{ return LESSEQUAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 193 "scan.l"
{ return GREATEREQUAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 194 "scan.l"
{ return GRLT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 196 "scan.l"
{ return TILDE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 197 "scan.l"
{ return CIRCUMFLEX; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 198 "scan.l"
{ return LEFTSHIFT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 199 "scan.l"
{ return RIGHTSHIFT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 200 "scan.l"
{ return DOUBLESTAR; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 202 "scan.l"
{ return PLUSEQUAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 203 "scan.l"
{ return MINEQUAL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 204 "scan.l"
{ return STAREQUAL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 205 "scan.l"
{ return SLASHEQUAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 206 "scan.l"
{ return PERCENTEQUAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 207 "scan.l"
{ return AMPEREQUAL; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 208 "scan.l"
{ return BAR; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 209 "scan.l"
{ return VBAREQUAL; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 210 "scan.l"
{ return CIRCUMFLEXEQUAL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 211 "scan.l"
{ return LEFTSHIFTEQUAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 212 "scan.l"
{ return RIGHTSHIFTEQUAL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 213 "scan.l"
{ return DOUBLESTAREQUAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 214 "scan.l"
{ return DOUBLESLASH; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 215 "scan.l"
{ return DOUBLESLASHEQUAL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 217 "scan.l"
{ return AT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 219 "scan.l"
{ return AND; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 220 "scan.l"
{ return AMPERSAND; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 221 "scan.l"
{ return NOT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 222 "scan.l"
{ return OR; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 223 "scan.l"
{ return AS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 224 "scan.l"
{ return ASSERT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 225 "scan.l"
{ return BREAK; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 226 "scan.l"
{ return CLASS; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 227 "scan.l"
{ return CONTINUE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 228 "scan.l"
{ return DEF; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 229 "scan.l"
{ return DEL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 230 "scan.l"
{ return ELIF; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 231 "scan.l"
{ return ELSE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 232 "scan.l"
{ return EXCEPT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 233 "scan.l"
{ return EXEC; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 234 "scan.l"
{ return FINALLY; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 235 "scan.l"
{ return FOR; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 236 "scan.l"
{ return FROM; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 237 "scan.l"
{ return GLOBAL; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 238 "scan.l"
{ return IF; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 239 "scan.l"
{ return IMPORT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 240 "scan.l"
{ return IN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 241 "scan.l"
{ return IS; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 242 "scan.l"
{ return LAMBDA; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 243 "scan.l"
{ return PASS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 244 "scan.l"
{ return PRINT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 245 "scan.l"
{ return RAISE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 246 "scan.l"
{ return RETURN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 247 "scan.l"
{ return TRY; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 248 "scan.l"
{ return WHILE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 249 "scan.l"
{ return WITH; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 250 "scan.l"
{ return YIELD; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 252 "scan.l"
{ 
                ++numbers;
                yylval.ast = new AstDouble(atof(yytext));
                return NUMBER;
              }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 257 "scan.l"
{ 
             ++numbers; 
             yylval.ast = new AstInt(atoi(yytext));
             return NUMBER; 
           }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 262 "scan.l"
{ 
             ++identifiers; 
             std::string s = std::string(yytext, yyleng);
             yylval.ast = new AstName(new std::string(yytext, yyleng));
             return NAME; 
           }
	YY_BREAK
case YY_STATE_EOF(INDENTING):
case YY_STATE_EOF(INITIAL):
#line 269 "scan.l"
{
             int t = calc_indent_change(0);
             BEGIN(FINISHING);
             unput('\n');
             if(t<0) return DEDENT;
           }
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 275 "scan.l"
{
             int t = calc_indent_change(0);
             unput('\n');
             if(t<0) return DEDENT;

             if( !given_endmarker ) { 
               given_endmarker = true; 
               return ENDMARKER; 
             }

             yyterminate();
           }
	YY_BREAK
case YY_STATE_EOF(LONG_STRING):
case YY_STATE_EOF(LONG_STRING2):
#line 289 "scan.l"

	YY_BREAK

case 99:
YY_RULE_SETUP
#line 291 "scan.l"

	YY_BREAK

case 100:
YY_RULE_SETUP
#line 293 "scan.l"
{ display_error("unexpected character"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 296 "scan.l"
ECHO;
	YY_BREAK
#line 1631 "lex.yy.c"
case YY_STATE_EOF(FINISHING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 305);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 296 "scan.l"



void 
init_scanner(FILE *input_file)
{
  yyin = input_file;
}

static void display_error(const char *msg) 
{ 
    fprintf(stderr, "%d: lexical error with [%s]: %s\n", 
            yylineno-1, yytext, msg);
    exit(EXIT_FAILURE);
}

/*                         { Z+ | iff indenting
 * calc_indent_change(thisIndent) -> { 0  | iff no indentation
 *                         { Z- | iff dedenting
 */
static int calc_indent_change(const int thisIndent) 
{ 
    int delta  = thisIndent-curr_indent;
    if (delta == 0 || encmatching > 0) {
        return 0; /* No indent */
    }
    if (delta >= 0) { /* Positive indent */
        curr_indent = thisIndent;
        indentations.push(delta);
        return delta;
    }
    /* Else, dedent. Possibly many */
    if ( indentations.empty() ) { /* Indentation mismatch */
        display_error("(internal) indentation stack underflow");
    }
    int prev_indent = indentations.top(); 
    indentations.pop();
    if ( prev_indent > -delta ) { /* Indentation mismatch */
        display_error("dedent is less than corresponding indent");
    }
    curr_indent -= prev_indent;
    return -prev_indent;
}

static int iced(const int t) 
{ 
    return t<0 ? DEDENT : INDENT; 
}

static int handle_indent(const int num_spaces)
{
    int t = calc_indent_change(num_spaces);
    if (t>=0) {
        BEGIN(INITIAL);
    } 
    if (t<0 || num_spaces==0) { /* undigest the token and go again */
        yyless(0);
        unput('\n'); 
        yyinput();
    }
    return t!=0 ? iced(t) : -1; 
}


static void left_enclose(void)
{
    ++encmatching;
}

static void right_enclose(void)
{
    --encmatching;
}


